services:
  ingest:
    container_name: ingest-data
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - USER_AGENT=Group 2 (+https://uit.no)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python ingest.py

  llm-chatbot-app:
    container_name: llm-chatbot-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - ingest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python app.py
